# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cdf6243814d82ed9370a205d19f4bae1477e010f967c2b1a06530d1b853b476f846f60b255ea0833498ade5007918f9a4c0a4a373a193ffd6f408342a8a2fdd

test:
  secret_key_base: a1849c3c6bbc2c4c769de84b7f311e0d0b13211164026ad14fc3252c4e638bd351bfa9cf1cfacd42249dc1fbd6fd0321d87d5316300a094123d6039c429331fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
